"""
Professional Referencing & Rig UI - Rig UI Manager Operators
Execute, validate, and manage rig UI scripts
"""

import bpy
from bpy.types import Operator

from ..core.library_utils import LibraryUtils
from ..core.script_injector import RigUIScriptInjector

class PROREF_OT_ExecuteRigUI(Operator):
    """Execute the rig UI script for selected character"""
    bl_idname = "proref.execute_rig_ui"
    bl_label = "Execute Rig UI"
    bl_description = "Execute the rig UI script for the selected character with proper context isolation"
    bl_options = {'REGISTER'}
    
    def execute(self, context):
        obj = context.active_object
        if not obj:
            self.report({'ERROR'}, "No active object")
            return {'CANCELLED'}
        
        # Find armature
        armature = LibraryUtils.find_armature_in_hierarchy(obj)
        if not armature:
            self.report({'ERROR'}, "No armature found in selection")
            return {'CANCELLED'}
        
        # Get script name
        script_name = armature.get("proref_rig_ui", "rig_ui.py")
        
        if script_name not in bpy.data.texts:
            self.report({'ERROR'}, f"Rig UI script '{script_name}' not found")
            return {'CANCELLED'}
        
        script = bpy.data.texts[script_name]
        
        # Execute with isolation
        success, error = RigUIScriptInjector.execute_isolated_script(armature, script)
        
        if success:
            self.report({'INFO'}, f"Executed {script_name} for {armature.name}")
            return {'FINISHED'}
        else:
            self.report({'ERROR'}, f"Execution failed: {error}")
            return {'CANCELLED'}


class PROREF_OT_ValidateRigUI(Operator):
    """Validate rig UI script for safety"""
    bl_idname = "proref.validate_rig_ui"
    bl_label = "Validate Rig UI Script"
    bl_description = "Check if the rig UI script is safe to execute"
    
    def execute(self, context):
        obj = context.active_object
        if not obj:
            self.report({'ERROR'}, "No active object")
            return {'CANCELLED'}
        
        armature = LibraryUtils.find_armature_in_hierarchy(obj)
        if not armature:
            self.report({'ERROR'}, "No armature found")
            return {'CANCELLED'}
        
        script_name = armature.get("proref_rig_ui", "rig_ui.py")
        
        if script_name not in bpy.data.texts:
            self.report({'ERROR'}, f"Script '{script_name}' not found")
            return {'CANCELLED'}
        
        script = bpy.data.texts[script_name]
        is_safe, warnings = RigUIScriptInjector.validate_script_safety(script)
        
        if is_safe:
            if warnings:
                msg = f"Script is safe but has {len(warnings)} warnings"
                self.report({'WARNING'}, msg)
                for warning in warnings:
                    print(f"  - {warning}")
            else:
                self.report({'INFO'}, "Script is safe to execute")
        else:
            self.report({'ERROR'}, "Script has critical safety issues")
            for warning in warnings:
                print(f"  - {warning}")
        
        return {'FINISHED'}


class PROREF_OT_CreateRigUIFromTemplate(Operator):
    """Create a new rig UI script from template"""
    bl_idname = "proref.create_rig_ui_template"
    bl_label = "Create Rig UI Template"
    bl_description = "Create a basic rig UI script template for the selected armature"
    bl_options = {'REGISTER', 'UNDO'}
    
    def execute(self, context):
        obj = context.active_object
        if not obj:
            self.report({'ERROR'}, "No active object")
            return {'CANCELLED'}
        
        armature = LibraryUtils.find_armature_in_hierarchy(obj)
        if not armature:
            self.report({'ERROR'}, "No armature found")
            return {'CANCELLED'}
        
        # Create template script
        script_name = f"rig_ui_{armature.name}.py"
        
        if script_name in bpy.data.texts:
            self.report({'WARNING'}, f"Script '{script_name}' already exists")
            return {'CANCELLED'}
        
        template = self._get_template(armature.name)
        
        script = bpy.data.texts.new(script_name)
        script.write(template)
        
        # Link to armature
        armature["proref_rig_ui"] = script_name
        
        self.report({'INFO'}, f"Created rig UI template: {script_name}")
        return {'FINISHED'}
    
    def _get_template(self, armature_name):
        """Get rig UI template"""
        return f'''"""
Rig UI Script for {armature_name}
Auto-generated by Professional Referencing addon
"""

import bpy

def create_rig_ui():
    """Create the rig UI panel"""
    armature = bpy.data.objects.get("{armature_name}")
    
    if not armature:
        print("Armature not found: {armature_name}")
        return
    
    # Your rig UI code here
    print(f"Rig UI loaded for {{armature.name}}")

# Execute on import
if __name__ == "__main__":
    create_rig_ui()
'''


class PROREF_OT_RefreshRigUI(Operator):
    """Refresh rig UI for all characters in scene"""
    bl_idname = "proref.refresh_all_rig_ui"
    bl_label = "Refresh All Rig UIs"
    bl_description = "Execute rig UI scripts for all characters with isolated scripts"
    
    def execute(self, context):
        executed_count = 0
        error_count = 0
        
        for obj in bpy.data.objects:
            if obj.type == 'ARMATURE' and "proref_rig_ui" in obj:
                script_name = obj["proref_rig_ui"]
                
                if script_name in bpy.data.texts:
                    script = bpy.data.texts[script_name]
                    success, error = RigUIScriptInjector.execute_isolated_script(obj, script)
                    
                    if success:
                        executed_count += 1
                    else:
                        error_count += 1
                        print(f"Failed to execute {script_name}: {error}")
        
        self.report({'INFO'}, f"Executed {executed_count} rig UIs ({error_count} errors)")
        return {'FINISHED'}


# Registration
classes = (
    PROREF_OT_ExecuteRigUI,
    PROREF_OT_ValidateRigUI,
    PROREF_OT_CreateRigUIFromTemplate,
    PROREF_OT_RefreshRigUI,
)

def register():
    for cls in classes:
        bpy.utils.register_class(cls)

def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
